# Generated by Django 2.0.5 on 2018-12-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0002_auto_20181215_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_video_format',
            field=models.CharField(choices=[('video/mp4', 'MP4'), ('video/webm', 'WebM'), ('video/ogg', 'Ogg')], default='video/webm', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='video_format',
            field=models.CharField(choices=[('video/mp4', 'MP4'), ('video/webm', 'WebM'), ('video/ogg', 'Ogg')], default='video/webm', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('arts_humanities', 'Arts and Humanities'), ('business', 'Business'), ('computer_science', 'Computer Science'), ('health_fitness', 'Health and Fitness'), ('languages', 'Languages'), ('math_logic', 'Math and Logic'), ('music', 'Music'), ('personal_developement', 'Personal Developement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
