# Generated by Django 2.0.5 on 2018-12-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0003_auto_20181217_1733'),
        ('learnify', '0003_auto_20181217_2141'),
    ]

    operations = [
    ]
