# Generated by Django 2.0.5 on 2018-12-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0003_auto_20181217_2141'),
        ('learnify', '0003_auto_20181217_1733'),
    ]

    operations = [
    ]
