# Generated by Django 2.0.5 on 2018-12-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0003_auto_20181223_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='poster',
            new_name='course_image',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='preview_video_format',
            new_name='video_format',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='order_number',
            new_name='lesson_number',
        ),
    ]
