# Generated by Django 2.0.5 on 2018-12-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnify', '0004_merge_20181217_2231'),
        ('learnify', '0004_merge_20181217_2152'),
    ]

    operations = [
    ]
